title: syon/til
description: Today I Learned
author: syon
github: https://github.com/syon/til
about: A fashion developer. Interested in life engineering.
disqus_shortname:
google_analytics: UA-37634759-2
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "https://twitter.com/syonxv"
    - icon: fa-linkedin
      link: "#"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/syon"

share:
  twitter_username: syonxv
  fb_appid:

urls:
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://syon.github.io"
baseurl: "/til"
permalink: /:year/:month/:day/:title/
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all

timezone: Asia/Tokyo

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
  - docker-compose.yml
  - vendor
