# Welcome to Jekyll!

# Site settings
title: syon/til
email:
description: >- # this means to ignore newlines until "baseurl:"
  Today I Learned.
baseurl: "/til"
url: "https://syon.github.io"
permalink: /:year/:month/:day/:title/
twitter_username: syonxv
github_username:  syon

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
